manifest_version: 1.0
project: inzibackend.Web.Core
root_path: I:\surpath150\src\inzibackend.Web.Core
created_at: 2025-09-29
total_folders: 28
documented: 15
pending: 13

folders_to_document:
  # Level 3 (deepest first)
  - path: I:/surpath150/src/inzibackend.Web.Core/UiCustomization/Metronic
    status: pending
    level: 3

  # Level 2
  - path: I:/surpath150/src/inzibackend.Web.Core/Common
    status: pending
    level: 2
  - path: I:/surpath150/src/inzibackend.Web.Core/DashboardCustomization
    status: pending
    level: 2
  - path: I:/surpath150/src/inzibackend.Web.Core/Extensions
    status: pending
    level: 2
  - path: I:/surpath150/src/inzibackend.Web.Core/HealthCheck
    status: pending
    level: 2
  - path: I:/surpath150/src/inzibackend.Web.Core/Helpers
    status: pending
    level: 2
  - path: I:/surpath150/src/inzibackend.Web.Core/IdentityServer
    status: pending
    level: 2
  - path: I:/surpath150/src/inzibackend.Web.Core/Navigation
    status: pending
    level: 2
  - path: I:/surpath150/src/inzibackend.Web.Core/Properties
    status: pending
    level: 2
  - path: I:/surpath150/src/inzibackend.Web.Core/Session
    status: pending
    level: 2
  - path: I:/surpath150/src/inzibackend.Web.Core/Swagger
    status: pending
    level: 2
  - path: I:/surpath150/src/inzibackend.Web.Core/UiCustomization
    status: pending
    level: 2
  - path: I:/surpath150/src/inzibackend.Web.Core/Url
    status: pending
    level: 2

already_documented:
  - I:/surpath150/src/inzibackend.Web.Core/Authentication/External
  - I:/surpath150/src/inzibackend.Web.Core/Authentication/JwtBearer
  - I:/surpath150/src/inzibackend.Web.Core/Authentication/TwoFactor
  - I:/surpath150/src/inzibackend.Web.Core/Authentication
  - I:/surpath150/src/inzibackend.Web.Core/Chat/SignalR
  - I:/surpath150/src/inzibackend.Web.Core/Chat
  - I:/surpath150/src/inzibackend.Web.Core/Configuration
  - I:/surpath150/src/inzibackend.Web.Core/Controllers
  - I:/surpath150/src/inzibackend.Web.Core/Models/Consent
  - I:/surpath150/src/inzibackend.Web.Core/Models/TokenAuth
  - I:/surpath150/src/inzibackend.Web.Core/Models
  - I:/surpath150/src/inzibackend.Web.Core/Security/Recaptcha
  - I:/surpath150/src/inzibackend.Web.Core/Security
  - I:/surpath150/src/inzibackend.Web.Core/Surpath
  - I:/surpath150/src/inzibackend.Web.Core

notes:
  - Excluding bin and obj folders
  - Processing bottom-up (deepest folders first)
  - Root folder needs update after subdocumentation complete