//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Surpath.CSTest.Macro {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MacroSoap", Namespace="http://clearstar.net/Gateway/Macro")]
    public partial class Macro : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddProfileMacroOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddProfileMacroCustomerAccessOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddServiceMacroOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddStatusMacroOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteProfileMacroOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteServiceMacroOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteStatusMacroOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMacroTemplateFieldsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetServiceMacroTemplateFieldsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProfileMacroOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProfileMacrosOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetServiceMacroOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetServiceMacrosOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStatusMacroOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStatusMacrosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessProfileMacroOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessServiceMacroOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessStatusMacroOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateProfileMacroOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateServiceMacroOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateStatusMacroOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Macro() {
            this.Url = global::Surpath.CSTest.Properties.Settings.Default.Surpath_Clearstar_CSTest_Macro_Macro;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddProfileMacroCompletedEventHandler AddProfileMacroCompleted;
        
        /// <remarks/>
        public event AddProfileMacroCustomerAccessCompletedEventHandler AddProfileMacroCustomerAccessCompleted;
        
        /// <remarks/>
        public event AddServiceMacroCompletedEventHandler AddServiceMacroCompleted;
        
        /// <remarks/>
        public event AddStatusMacroCompletedEventHandler AddStatusMacroCompleted;
        
        /// <remarks/>
        public event DeleteProfileMacroCompletedEventHandler DeleteProfileMacroCompleted;
        
        /// <remarks/>
        public event DeleteServiceMacroCompletedEventHandler DeleteServiceMacroCompleted;
        
        /// <remarks/>
        public event DeleteStatusMacroCompletedEventHandler DeleteStatusMacroCompleted;
        
        /// <remarks/>
        public event GetMacroTemplateFieldsCompletedEventHandler GetMacroTemplateFieldsCompleted;
        
        /// <remarks/>
        public event GetServiceMacroTemplateFieldsCompletedEventHandler GetServiceMacroTemplateFieldsCompleted;
        
        /// <remarks/>
        public event GetProfileMacroCompletedEventHandler GetProfileMacroCompleted;
        
        /// <remarks/>
        public event GetProfileMacrosCompletedEventHandler GetProfileMacrosCompleted;
        
        /// <remarks/>
        public event GetServiceMacroCompletedEventHandler GetServiceMacroCompleted;
        
        /// <remarks/>
        public event GetServiceMacrosCompletedEventHandler GetServiceMacrosCompleted;
        
        /// <remarks/>
        public event GetStatusMacroCompletedEventHandler GetStatusMacroCompleted;
        
        /// <remarks/>
        public event GetStatusMacrosCompletedEventHandler GetStatusMacrosCompleted;
        
        /// <remarks/>
        public event ProcessProfileMacroCompletedEventHandler ProcessProfileMacroCompleted;
        
        /// <remarks/>
        public event ProcessServiceMacroCompletedEventHandler ProcessServiceMacroCompleted;
        
        /// <remarks/>
        public event ProcessStatusMacroCompletedEventHandler ProcessStatusMacroCompleted;
        
        /// <remarks/>
        public event UpdateProfileMacroCompletedEventHandler UpdateProfileMacroCompleted;
        
        /// <remarks/>
        public event UpdateServiceMacroCompletedEventHandler UpdateServiceMacroCompleted;
        
        /// <remarks/>
        public event UpdateStatusMacroCompletedEventHandler UpdateStatusMacroCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/Macro/AddProfileMacro", RequestNamespace="http://clearstar.net/Gateway/Macro", ResponseNamespace="http://clearstar.net/Gateway/Macro", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode AddProfileMacro(string sUserName, string sPassword, int iBOID, string sCustID, string sMacroName, string sMacroText, int[] iTemplateFieldIDs) {
            object[] results = this.Invoke("AddProfileMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        sMacroName,
                        sMacroText,
                        iTemplateFieldIDs});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void AddProfileMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, string sMacroName, string sMacroText, int[] iTemplateFieldIDs) {
            this.AddProfileMacroAsync(sUserName, sPassword, iBOID, sCustID, sMacroName, sMacroText, iTemplateFieldIDs, null);
        }
        
        /// <remarks/>
        public void AddProfileMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, string sMacroName, string sMacroText, int[] iTemplateFieldIDs, object userState) {
            if ((this.AddProfileMacroOperationCompleted == null)) {
                this.AddProfileMacroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddProfileMacroOperationCompleted);
            }
            this.InvokeAsync("AddProfileMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        sMacroName,
                        sMacroText,
                        iTemplateFieldIDs}, this.AddProfileMacroOperationCompleted, userState);
        }
        
        private void OnAddProfileMacroOperationCompleted(object arg) {
            if ((this.AddProfileMacroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddProfileMacroCompleted(this, new AddProfileMacroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/Macro/AddProfileMacroCustomerAccess", RequestNamespace="http://clearstar.net/Gateway/Macro", ResponseNamespace="http://clearstar.net/Gateway/Macro", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode AddProfileMacroCustomerAccess(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID, bool bIsAvailableToAllCustomers, string[] sCustomerIDs) {
            object[] results = this.Invoke("AddProfileMacroCustomerAccess", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iMacroID,
                        bIsAvailableToAllCustomers,
                        sCustomerIDs});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void AddProfileMacroCustomerAccessAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID, bool bIsAvailableToAllCustomers, string[] sCustomerIDs) {
            this.AddProfileMacroCustomerAccessAsync(sUserName, sPassword, iBOID, sCustID, iMacroID, bIsAvailableToAllCustomers, sCustomerIDs, null);
        }
        
        /// <remarks/>
        public void AddProfileMacroCustomerAccessAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID, bool bIsAvailableToAllCustomers, string[] sCustomerIDs, object userState) {
            if ((this.AddProfileMacroCustomerAccessOperationCompleted == null)) {
                this.AddProfileMacroCustomerAccessOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddProfileMacroCustomerAccessOperationCompleted);
            }
            this.InvokeAsync("AddProfileMacroCustomerAccess", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iMacroID,
                        bIsAvailableToAllCustomers,
                        sCustomerIDs}, this.AddProfileMacroCustomerAccessOperationCompleted, userState);
        }
        
        private void OnAddProfileMacroCustomerAccessOperationCompleted(object arg) {
            if ((this.AddProfileMacroCustomerAccessCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddProfileMacroCustomerAccessCompleted(this, new AddProfileMacroCustomerAccessCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/Macro/AddServiceMacro", RequestNamespace="http://clearstar.net/Gateway/Macro", ResponseNamespace="http://clearstar.net/Gateway/Macro", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode AddServiceMacro(string sUserName, string sPassword, int iBOID, string sCustID, int iSourceID, string sServiceNo, string sMacroName, string sMacroText, int[] iTemplateFieldIDs) {
            object[] results = this.Invoke("AddServiceMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iSourceID,
                        sServiceNo,
                        sMacroName,
                        sMacroText,
                        iTemplateFieldIDs});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void AddServiceMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iSourceID, string sServiceNo, string sMacroName, string sMacroText, int[] iTemplateFieldIDs) {
            this.AddServiceMacroAsync(sUserName, sPassword, iBOID, sCustID, iSourceID, sServiceNo, sMacroName, sMacroText, iTemplateFieldIDs, null);
        }
        
        /// <remarks/>
        public void AddServiceMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iSourceID, string sServiceNo, string sMacroName, string sMacroText, int[] iTemplateFieldIDs, object userState) {
            if ((this.AddServiceMacroOperationCompleted == null)) {
                this.AddServiceMacroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddServiceMacroOperationCompleted);
            }
            this.InvokeAsync("AddServiceMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iSourceID,
                        sServiceNo,
                        sMacroName,
                        sMacroText,
                        iTemplateFieldIDs}, this.AddServiceMacroOperationCompleted, userState);
        }
        
        private void OnAddServiceMacroOperationCompleted(object arg) {
            if ((this.AddServiceMacroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddServiceMacroCompleted(this, new AddServiceMacroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/Macro/AddStatusMacro", RequestNamespace="http://clearstar.net/Gateway/Macro", ResponseNamespace="http://clearstar.net/Gateway/Macro", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode AddStatusMacro(string sUserName, string sPassword, int iBOID, string sCustID, string sMacroName, string sMacroText, string availableToSupplier, string availableToCustomer, int[] iTemplateFieldIDs) {
            object[] results = this.Invoke("AddStatusMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        sMacroName,
                        sMacroText,
                        availableToSupplier,
                        availableToCustomer,
                        iTemplateFieldIDs});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void AddStatusMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, string sMacroName, string sMacroText, string availableToSupplier, string availableToCustomer, int[] iTemplateFieldIDs) {
            this.AddStatusMacroAsync(sUserName, sPassword, iBOID, sCustID, sMacroName, sMacroText, availableToSupplier, availableToCustomer, iTemplateFieldIDs, null);
        }
        
        /// <remarks/>
        public void AddStatusMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, string sMacroName, string sMacroText, string availableToSupplier, string availableToCustomer, int[] iTemplateFieldIDs, object userState) {
            if ((this.AddStatusMacroOperationCompleted == null)) {
                this.AddStatusMacroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddStatusMacroOperationCompleted);
            }
            this.InvokeAsync("AddStatusMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        sMacroName,
                        sMacroText,
                        availableToSupplier,
                        availableToCustomer,
                        iTemplateFieldIDs}, this.AddStatusMacroOperationCompleted, userState);
        }
        
        private void OnAddStatusMacroOperationCompleted(object arg) {
            if ((this.AddStatusMacroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddStatusMacroCompleted(this, new AddStatusMacroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/Macro/DeleteProfileMacro", RequestNamespace="http://clearstar.net/Gateway/Macro", ResponseNamespace="http://clearstar.net/Gateway/Macro", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode DeleteProfileMacro(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID) {
            object[] results = this.Invoke("DeleteProfileMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iMacroID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteProfileMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID) {
            this.DeleteProfileMacroAsync(sUserName, sPassword, iBOID, sCustID, iMacroID, null);
        }
        
        /// <remarks/>
        public void DeleteProfileMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID, object userState) {
            if ((this.DeleteProfileMacroOperationCompleted == null)) {
                this.DeleteProfileMacroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteProfileMacroOperationCompleted);
            }
            this.InvokeAsync("DeleteProfileMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iMacroID}, this.DeleteProfileMacroOperationCompleted, userState);
        }
        
        private void OnDeleteProfileMacroOperationCompleted(object arg) {
            if ((this.DeleteProfileMacroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteProfileMacroCompleted(this, new DeleteProfileMacroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/Macro/DeleteServiceMacro", RequestNamespace="http://clearstar.net/Gateway/Macro", ResponseNamespace="http://clearstar.net/Gateway/Macro", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode DeleteServiceMacro(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID) {
            object[] results = this.Invoke("DeleteServiceMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iMacroID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteServiceMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID) {
            this.DeleteServiceMacroAsync(sUserName, sPassword, iBOID, sCustID, iMacroID, null);
        }
        
        /// <remarks/>
        public void DeleteServiceMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID, object userState) {
            if ((this.DeleteServiceMacroOperationCompleted == null)) {
                this.DeleteServiceMacroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteServiceMacroOperationCompleted);
            }
            this.InvokeAsync("DeleteServiceMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iMacroID}, this.DeleteServiceMacroOperationCompleted, userState);
        }
        
        private void OnDeleteServiceMacroOperationCompleted(object arg) {
            if ((this.DeleteServiceMacroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteServiceMacroCompleted(this, new DeleteServiceMacroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/Macro/DeleteStatusMacro", RequestNamespace="http://clearstar.net/Gateway/Macro", ResponseNamespace="http://clearstar.net/Gateway/Macro", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode DeleteStatusMacro(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID) {
            object[] results = this.Invoke("DeleteStatusMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iMacroID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteStatusMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID) {
            this.DeleteStatusMacroAsync(sUserName, sPassword, iBOID, sCustID, iMacroID, null);
        }
        
        /// <remarks/>
        public void DeleteStatusMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID, object userState) {
            if ((this.DeleteStatusMacroOperationCompleted == null)) {
                this.DeleteStatusMacroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteStatusMacroOperationCompleted);
            }
            this.InvokeAsync("DeleteStatusMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iMacroID}, this.DeleteStatusMacroOperationCompleted, userState);
        }
        
        private void OnDeleteStatusMacroOperationCompleted(object arg) {
            if ((this.DeleteStatusMacroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteStatusMacroCompleted(this, new DeleteStatusMacroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/Macro/GetMacroTemplateFields", RequestNamespace="http://clearstar.net/Gateway/Macro", ResponseNamespace="http://clearstar.net/Gateway/Macro", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetMacroTemplateFields(string sUserName, string sPassword, int iBOID, string sCustID, char cMappedTo) {
            object[] results = this.Invoke("GetMacroTemplateFields", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        cMappedTo});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetMacroTemplateFieldsAsync(string sUserName, string sPassword, int iBOID, string sCustID, char cMappedTo) {
            this.GetMacroTemplateFieldsAsync(sUserName, sPassword, iBOID, sCustID, cMappedTo, null);
        }
        
        /// <remarks/>
        public void GetMacroTemplateFieldsAsync(string sUserName, string sPassword, int iBOID, string sCustID, char cMappedTo, object userState) {
            if ((this.GetMacroTemplateFieldsOperationCompleted == null)) {
                this.GetMacroTemplateFieldsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMacroTemplateFieldsOperationCompleted);
            }
            this.InvokeAsync("GetMacroTemplateFields", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        cMappedTo}, this.GetMacroTemplateFieldsOperationCompleted, userState);
        }
        
        private void OnGetMacroTemplateFieldsOperationCompleted(object arg) {
            if ((this.GetMacroTemplateFieldsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMacroTemplateFieldsCompleted(this, new GetMacroTemplateFieldsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/Macro/GetServiceMacroTemplateFields", RequestNamespace="http://clearstar.net/Gateway/Macro", ResponseNamespace="http://clearstar.net/Gateway/Macro", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetServiceMacroTemplateFields(string sUserName, string sPassword, int iBOID, string sCustID, string sServiceNo) {
            object[] results = this.Invoke("GetServiceMacroTemplateFields", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        sServiceNo});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetServiceMacroTemplateFieldsAsync(string sUserName, string sPassword, int iBOID, string sCustID, string sServiceNo) {
            this.GetServiceMacroTemplateFieldsAsync(sUserName, sPassword, iBOID, sCustID, sServiceNo, null);
        }
        
        /// <remarks/>
        public void GetServiceMacroTemplateFieldsAsync(string sUserName, string sPassword, int iBOID, string sCustID, string sServiceNo, object userState) {
            if ((this.GetServiceMacroTemplateFieldsOperationCompleted == null)) {
                this.GetServiceMacroTemplateFieldsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServiceMacroTemplateFieldsOperationCompleted);
            }
            this.InvokeAsync("GetServiceMacroTemplateFields", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        sServiceNo}, this.GetServiceMacroTemplateFieldsOperationCompleted, userState);
        }
        
        private void OnGetServiceMacroTemplateFieldsOperationCompleted(object arg) {
            if ((this.GetServiceMacroTemplateFieldsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServiceMacroTemplateFieldsCompleted(this, new GetServiceMacroTemplateFieldsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/Macro/GetProfileMacro", RequestNamespace="http://clearstar.net/Gateway/Macro", ResponseNamespace="http://clearstar.net/Gateway/Macro", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetProfileMacro(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID) {
            object[] results = this.Invoke("GetProfileMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iMacroID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetProfileMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID) {
            this.GetProfileMacroAsync(sUserName, sPassword, iBOID, sCustID, iMacroID, null);
        }
        
        /// <remarks/>
        public void GetProfileMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID, object userState) {
            if ((this.GetProfileMacroOperationCompleted == null)) {
                this.GetProfileMacroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProfileMacroOperationCompleted);
            }
            this.InvokeAsync("GetProfileMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iMacroID}, this.GetProfileMacroOperationCompleted, userState);
        }
        
        private void OnGetProfileMacroOperationCompleted(object arg) {
            if ((this.GetProfileMacroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProfileMacroCompleted(this, new GetProfileMacroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/Macro/GetProfileMacros", RequestNamespace="http://clearstar.net/Gateway/Macro", ResponseNamespace="http://clearstar.net/Gateway/Macro", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetProfileMacros(string sUserName, string sPassword, int iBOID, string sCustID) {
            object[] results = this.Invoke("GetProfileMacros", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetProfileMacrosAsync(string sUserName, string sPassword, int iBOID, string sCustID) {
            this.GetProfileMacrosAsync(sUserName, sPassword, iBOID, sCustID, null);
        }
        
        /// <remarks/>
        public void GetProfileMacrosAsync(string sUserName, string sPassword, int iBOID, string sCustID, object userState) {
            if ((this.GetProfileMacrosOperationCompleted == null)) {
                this.GetProfileMacrosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProfileMacrosOperationCompleted);
            }
            this.InvokeAsync("GetProfileMacros", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID}, this.GetProfileMacrosOperationCompleted, userState);
        }
        
        private void OnGetProfileMacrosOperationCompleted(object arg) {
            if ((this.GetProfileMacrosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProfileMacrosCompleted(this, new GetProfileMacrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/Macro/GetServiceMacro", RequestNamespace="http://clearstar.net/Gateway/Macro", ResponseNamespace="http://clearstar.net/Gateway/Macro", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetServiceMacro(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID) {
            object[] results = this.Invoke("GetServiceMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iMacroID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetServiceMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID) {
            this.GetServiceMacroAsync(sUserName, sPassword, iBOID, sCustID, iMacroID, null);
        }
        
        /// <remarks/>
        public void GetServiceMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID, object userState) {
            if ((this.GetServiceMacroOperationCompleted == null)) {
                this.GetServiceMacroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServiceMacroOperationCompleted);
            }
            this.InvokeAsync("GetServiceMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iMacroID}, this.GetServiceMacroOperationCompleted, userState);
        }
        
        private void OnGetServiceMacroOperationCompleted(object arg) {
            if ((this.GetServiceMacroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServiceMacroCompleted(this, new GetServiceMacroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/Macro/GetServiceMacros", RequestNamespace="http://clearstar.net/Gateway/Macro", ResponseNamespace="http://clearstar.net/Gateway/Macro", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetServiceMacros(string sUserName, string sPassword, int iBOID, string sCustID, int iSourceID, string sServiceNo) {
            object[] results = this.Invoke("GetServiceMacros", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iSourceID,
                        sServiceNo});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetServiceMacrosAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iSourceID, string sServiceNo) {
            this.GetServiceMacrosAsync(sUserName, sPassword, iBOID, sCustID, iSourceID, sServiceNo, null);
        }
        
        /// <remarks/>
        public void GetServiceMacrosAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iSourceID, string sServiceNo, object userState) {
            if ((this.GetServiceMacrosOperationCompleted == null)) {
                this.GetServiceMacrosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServiceMacrosOperationCompleted);
            }
            this.InvokeAsync("GetServiceMacros", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iSourceID,
                        sServiceNo}, this.GetServiceMacrosOperationCompleted, userState);
        }
        
        private void OnGetServiceMacrosOperationCompleted(object arg) {
            if ((this.GetServiceMacrosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServiceMacrosCompleted(this, new GetServiceMacrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/Macro/GetStatusMacro", RequestNamespace="http://clearstar.net/Gateway/Macro", ResponseNamespace="http://clearstar.net/Gateway/Macro", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetStatusMacro(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID) {
            object[] results = this.Invoke("GetStatusMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iMacroID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetStatusMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID) {
            this.GetStatusMacroAsync(sUserName, sPassword, iBOID, sCustID, iMacroID, null);
        }
        
        /// <remarks/>
        public void GetStatusMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID, object userState) {
            if ((this.GetStatusMacroOperationCompleted == null)) {
                this.GetStatusMacroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStatusMacroOperationCompleted);
            }
            this.InvokeAsync("GetStatusMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iMacroID}, this.GetStatusMacroOperationCompleted, userState);
        }
        
        private void OnGetStatusMacroOperationCompleted(object arg) {
            if ((this.GetStatusMacroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStatusMacroCompleted(this, new GetStatusMacroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/Macro/GetStatusMacros", RequestNamespace="http://clearstar.net/Gateway/Macro", ResponseNamespace="http://clearstar.net/Gateway/Macro", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetStatusMacros(string sUserName, string sPassword, int iBOID, string sCustID) {
            object[] results = this.Invoke("GetStatusMacros", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetStatusMacrosAsync(string sUserName, string sPassword, int iBOID, string sCustID) {
            this.GetStatusMacrosAsync(sUserName, sPassword, iBOID, sCustID, null);
        }
        
        /// <remarks/>
        public void GetStatusMacrosAsync(string sUserName, string sPassword, int iBOID, string sCustID, object userState) {
            if ((this.GetStatusMacrosOperationCompleted == null)) {
                this.GetStatusMacrosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStatusMacrosOperationCompleted);
            }
            this.InvokeAsync("GetStatusMacros", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID}, this.GetStatusMacrosOperationCompleted, userState);
        }
        
        private void OnGetStatusMacrosOperationCompleted(object arg) {
            if ((this.GetStatusMacrosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStatusMacrosCompleted(this, new GetStatusMacrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/Macro/ProcessProfileMacro", RequestNamespace="http://clearstar.net/Gateway/Macro", ResponseNamespace="http://clearstar.net/Gateway/Macro", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ProcessProfileMacro(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID, string sProfNo) {
            object[] results = this.Invoke("ProcessProfileMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iMacroID,
                        sProfNo});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessProfileMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID, string sProfNo) {
            this.ProcessProfileMacroAsync(sUserName, sPassword, iBOID, sCustID, iMacroID, sProfNo, null);
        }
        
        /// <remarks/>
        public void ProcessProfileMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID, string sProfNo, object userState) {
            if ((this.ProcessProfileMacroOperationCompleted == null)) {
                this.ProcessProfileMacroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessProfileMacroOperationCompleted);
            }
            this.InvokeAsync("ProcessProfileMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iMacroID,
                        sProfNo}, this.ProcessProfileMacroOperationCompleted, userState);
        }
        
        private void OnProcessProfileMacroOperationCompleted(object arg) {
            if ((this.ProcessProfileMacroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessProfileMacroCompleted(this, new ProcessProfileMacroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/Macro/ProcessServiceMacro", RequestNamespace="http://clearstar.net/Gateway/Macro", ResponseNamespace="http://clearstar.net/Gateway/Macro", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ProcessServiceMacro(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID, int iSourceID, int iOrderID, string sServiceNo) {
            object[] results = this.Invoke("ProcessServiceMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iMacroID,
                        iSourceID,
                        iOrderID,
                        sServiceNo});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessServiceMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID, int iSourceID, int iOrderID, string sServiceNo) {
            this.ProcessServiceMacroAsync(sUserName, sPassword, iBOID, sCustID, iMacroID, iSourceID, iOrderID, sServiceNo, null);
        }
        
        /// <remarks/>
        public void ProcessServiceMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID, int iSourceID, int iOrderID, string sServiceNo, object userState) {
            if ((this.ProcessServiceMacroOperationCompleted == null)) {
                this.ProcessServiceMacroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessServiceMacroOperationCompleted);
            }
            this.InvokeAsync("ProcessServiceMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iMacroID,
                        iSourceID,
                        iOrderID,
                        sServiceNo}, this.ProcessServiceMacroOperationCompleted, userState);
        }
        
        private void OnProcessServiceMacroOperationCompleted(object arg) {
            if ((this.ProcessServiceMacroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessServiceMacroCompleted(this, new ProcessServiceMacroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/Macro/ProcessStatusMacro", RequestNamespace="http://clearstar.net/Gateway/Macro", ResponseNamespace="http://clearstar.net/Gateway/Macro", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ProcessStatusMacro(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID, int iSourceID, int iOrderID) {
            object[] results = this.Invoke("ProcessStatusMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iMacroID,
                        iSourceID,
                        iOrderID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessStatusMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID, int iSourceID, int iOrderID) {
            this.ProcessStatusMacroAsync(sUserName, sPassword, iBOID, sCustID, iMacroID, iSourceID, iOrderID, null);
        }
        
        /// <remarks/>
        public void ProcessStatusMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID, int iSourceID, int iOrderID, object userState) {
            if ((this.ProcessStatusMacroOperationCompleted == null)) {
                this.ProcessStatusMacroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessStatusMacroOperationCompleted);
            }
            this.InvokeAsync("ProcessStatusMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iMacroID,
                        iSourceID,
                        iOrderID}, this.ProcessStatusMacroOperationCompleted, userState);
        }
        
        private void OnProcessStatusMacroOperationCompleted(object arg) {
            if ((this.ProcessStatusMacroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessStatusMacroCompleted(this, new ProcessStatusMacroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/Macro/UpdateProfileMacro", RequestNamespace="http://clearstar.net/Gateway/Macro", ResponseNamespace="http://clearstar.net/Gateway/Macro", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode UpdateProfileMacro(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID, string sMacroName, string sMacroText, int[] iTemplateFieldIDs) {
            object[] results = this.Invoke("UpdateProfileMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iMacroID,
                        sMacroName,
                        sMacroText,
                        iTemplateFieldIDs});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateProfileMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID, string sMacroName, string sMacroText, int[] iTemplateFieldIDs) {
            this.UpdateProfileMacroAsync(sUserName, sPassword, iBOID, sCustID, iMacroID, sMacroName, sMacroText, iTemplateFieldIDs, null);
        }
        
        /// <remarks/>
        public void UpdateProfileMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID, string sMacroName, string sMacroText, int[] iTemplateFieldIDs, object userState) {
            if ((this.UpdateProfileMacroOperationCompleted == null)) {
                this.UpdateProfileMacroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateProfileMacroOperationCompleted);
            }
            this.InvokeAsync("UpdateProfileMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iMacroID,
                        sMacroName,
                        sMacroText,
                        iTemplateFieldIDs}, this.UpdateProfileMacroOperationCompleted, userState);
        }
        
        private void OnUpdateProfileMacroOperationCompleted(object arg) {
            if ((this.UpdateProfileMacroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateProfileMacroCompleted(this, new UpdateProfileMacroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/Macro/UpdateServiceMacro", RequestNamespace="http://clearstar.net/Gateway/Macro", ResponseNamespace="http://clearstar.net/Gateway/Macro", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode UpdateServiceMacro(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID, int iSourceID, string sMacroName, string sMacroText, int[] iTemplateFieldIDs, string sServiceNo) {
            object[] results = this.Invoke("UpdateServiceMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iMacroID,
                        iSourceID,
                        sMacroName,
                        sMacroText,
                        iTemplateFieldIDs,
                        sServiceNo});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateServiceMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID, int iSourceID, string sMacroName, string sMacroText, int[] iTemplateFieldIDs, string sServiceNo) {
            this.UpdateServiceMacroAsync(sUserName, sPassword, iBOID, sCustID, iMacroID, iSourceID, sMacroName, sMacroText, iTemplateFieldIDs, sServiceNo, null);
        }
        
        /// <remarks/>
        public void UpdateServiceMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID, int iSourceID, string sMacroName, string sMacroText, int[] iTemplateFieldIDs, string sServiceNo, object userState) {
            if ((this.UpdateServiceMacroOperationCompleted == null)) {
                this.UpdateServiceMacroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateServiceMacroOperationCompleted);
            }
            this.InvokeAsync("UpdateServiceMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iMacroID,
                        iSourceID,
                        sMacroName,
                        sMacroText,
                        iTemplateFieldIDs,
                        sServiceNo}, this.UpdateServiceMacroOperationCompleted, userState);
        }
        
        private void OnUpdateServiceMacroOperationCompleted(object arg) {
            if ((this.UpdateServiceMacroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateServiceMacroCompleted(this, new UpdateServiceMacroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/Macro/UpdateStatusMacro", RequestNamespace="http://clearstar.net/Gateway/Macro", ResponseNamespace="http://clearstar.net/Gateway/Macro", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode UpdateStatusMacro(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID, string sMacroName, string sMacroText, string availableToSupplier, string availableToCustomer, int[] iTemplateFieldIDs) {
            object[] results = this.Invoke("UpdateStatusMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iMacroID,
                        sMacroName,
                        sMacroText,
                        availableToSupplier,
                        availableToCustomer,
                        iTemplateFieldIDs});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateStatusMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID, string sMacroName, string sMacroText, string availableToSupplier, string availableToCustomer, int[] iTemplateFieldIDs) {
            this.UpdateStatusMacroAsync(sUserName, sPassword, iBOID, sCustID, iMacroID, sMacroName, sMacroText, availableToSupplier, availableToCustomer, iTemplateFieldIDs, null);
        }
        
        /// <remarks/>
        public void UpdateStatusMacroAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iMacroID, string sMacroName, string sMacroText, string availableToSupplier, string availableToCustomer, int[] iTemplateFieldIDs, object userState) {
            if ((this.UpdateStatusMacroOperationCompleted == null)) {
                this.UpdateStatusMacroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateStatusMacroOperationCompleted);
            }
            this.InvokeAsync("UpdateStatusMacro", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iMacroID,
                        sMacroName,
                        sMacroText,
                        availableToSupplier,
                        availableToCustomer,
                        iTemplateFieldIDs}, this.UpdateStatusMacroOperationCompleted, userState);
        }
        
        private void OnUpdateStatusMacroOperationCompleted(object arg) {
            if ((this.UpdateStatusMacroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateStatusMacroCompleted(this, new UpdateStatusMacroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void AddProfileMacroCompletedEventHandler(object sender, AddProfileMacroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddProfileMacroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddProfileMacroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void AddProfileMacroCustomerAccessCompletedEventHandler(object sender, AddProfileMacroCustomerAccessCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddProfileMacroCustomerAccessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddProfileMacroCustomerAccessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void AddServiceMacroCompletedEventHandler(object sender, AddServiceMacroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddServiceMacroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddServiceMacroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void AddStatusMacroCompletedEventHandler(object sender, AddStatusMacroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddStatusMacroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddStatusMacroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void DeleteProfileMacroCompletedEventHandler(object sender, DeleteProfileMacroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteProfileMacroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteProfileMacroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void DeleteServiceMacroCompletedEventHandler(object sender, DeleteServiceMacroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteServiceMacroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteServiceMacroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void DeleteStatusMacroCompletedEventHandler(object sender, DeleteStatusMacroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteStatusMacroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteStatusMacroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetMacroTemplateFieldsCompletedEventHandler(object sender, GetMacroTemplateFieldsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMacroTemplateFieldsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMacroTemplateFieldsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetServiceMacroTemplateFieldsCompletedEventHandler(object sender, GetServiceMacroTemplateFieldsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServiceMacroTemplateFieldsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServiceMacroTemplateFieldsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetProfileMacroCompletedEventHandler(object sender, GetProfileMacroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProfileMacroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProfileMacroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetProfileMacrosCompletedEventHandler(object sender, GetProfileMacrosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProfileMacrosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProfileMacrosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetServiceMacroCompletedEventHandler(object sender, GetServiceMacroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServiceMacroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServiceMacroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetServiceMacrosCompletedEventHandler(object sender, GetServiceMacrosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServiceMacrosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServiceMacrosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetStatusMacroCompletedEventHandler(object sender, GetStatusMacroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStatusMacroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStatusMacroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetStatusMacrosCompletedEventHandler(object sender, GetStatusMacrosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStatusMacrosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStatusMacrosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ProcessProfileMacroCompletedEventHandler(object sender, ProcessProfileMacroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessProfileMacroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessProfileMacroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ProcessServiceMacroCompletedEventHandler(object sender, ProcessServiceMacroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessServiceMacroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessServiceMacroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ProcessStatusMacroCompletedEventHandler(object sender, ProcessStatusMacroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessStatusMacroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessStatusMacroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void UpdateProfileMacroCompletedEventHandler(object sender, UpdateProfileMacroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateProfileMacroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateProfileMacroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void UpdateServiceMacroCompletedEventHandler(object sender, UpdateServiceMacroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateServiceMacroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateServiceMacroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void UpdateStatusMacroCompletedEventHandler(object sender, UpdateStatusMacroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateStatusMacroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateStatusMacroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591