//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Surpath.Clearstar.CS.Supplier {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SupplierSoap", Namespace="http://clearstar.net/Gateway/wsSupplier/")]
    public partial class Supplier : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetServiceMacrosOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveOrderResultsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveOrderResultsDraftProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveOrderStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrderDocumentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInternalSupplierOrderSummaryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetExternalSupplierOrderSummaryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListOfOrdersForSupplierOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNewOrdersMarkInProgressOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Supplier() {
            this.Url = global::Surpath.Clearstar.Properties.Settings.Default.Surpath_Clearstar_CS_Supplier_Supplier;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetServiceMacrosCompletedEventHandler GetServiceMacrosCompleted;
        
        /// <remarks/>
        public event RetrieveOrdersCompletedEventHandler RetrieveOrdersCompleted;
        
        /// <remarks/>
        public event SearchOrdersCompletedEventHandler SearchOrdersCompleted;
        
        /// <remarks/>
        public event SaveOrderResultsCompletedEventHandler SaveOrderResultsCompleted;
        
        /// <remarks/>
        public event SaveOrderResultsDraftProfileCompletedEventHandler SaveOrderResultsDraftProfileCompleted;
        
        /// <remarks/>
        public event SaveOrderStatusCompletedEventHandler SaveOrderStatusCompleted;
        
        /// <remarks/>
        public event GetOrderDocumentsCompletedEventHandler GetOrderDocumentsCompleted;
        
        /// <remarks/>
        public event GetInternalSupplierOrderSummaryCompletedEventHandler GetInternalSupplierOrderSummaryCompleted;
        
        /// <remarks/>
        public event GetExternalSupplierOrderSummaryCompletedEventHandler GetExternalSupplierOrderSummaryCompleted;
        
        /// <remarks/>
        public event GetListOfOrdersForSupplierCompletedEventHandler GetListOfOrdersForSupplierCompleted;
        
        /// <remarks/>
        public event GetNewOrdersMarkInProgressCompletedEventHandler GetNewOrdersMarkInProgressCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/wsSupplier/GetServiceMacros", RequestNamespace="http://clearstar.net/Gateway/wsSupplier/", ResponseNamespace="http://clearstar.net/Gateway/wsSupplier/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetServiceMacros(string sUserName, string sPassword, int iBOID, int iSourceID, string sServiceNo) {
            object[] results = this.Invoke("GetServiceMacros", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        iSourceID,
                        sServiceNo});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetServiceMacrosAsync(string sUserName, string sPassword, int iBOID, int iSourceID, string sServiceNo) {
            this.GetServiceMacrosAsync(sUserName, sPassword, iBOID, iSourceID, sServiceNo, null);
        }
        
        /// <remarks/>
        public void GetServiceMacrosAsync(string sUserName, string sPassword, int iBOID, int iSourceID, string sServiceNo, object userState) {
            if ((this.GetServiceMacrosOperationCompleted == null)) {
                this.GetServiceMacrosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServiceMacrosOperationCompleted);
            }
            this.InvokeAsync("GetServiceMacros", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        iSourceID,
                        sServiceNo}, this.GetServiceMacrosOperationCompleted, userState);
        }
        
        private void OnGetServiceMacrosOperationCompleted(object arg) {
            if ((this.GetServiceMacrosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServiceMacrosCompleted(this, new GetServiceMacrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/wsSupplier/RetrieveOrders", RequestNamespace="http://clearstar.net/Gateway/wsSupplier/", ResponseNamespace="http://clearstar.net/Gateway/wsSupplier/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode RetrieveOrders(string sUserName, string sPassword, int iBOID, int iSourceID, string sOption, int iOrderID, bool bUseBatchID, string sBatch) {
            object[] results = this.Invoke("RetrieveOrders", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        iSourceID,
                        sOption,
                        iOrderID,
                        bUseBatchID,
                        sBatch});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveOrdersAsync(string sUserName, string sPassword, int iBOID, int iSourceID, string sOption, int iOrderID, bool bUseBatchID, string sBatch) {
            this.RetrieveOrdersAsync(sUserName, sPassword, iBOID, iSourceID, sOption, iOrderID, bUseBatchID, sBatch, null);
        }
        
        /// <remarks/>
        public void RetrieveOrdersAsync(string sUserName, string sPassword, int iBOID, int iSourceID, string sOption, int iOrderID, bool bUseBatchID, string sBatch, object userState) {
            if ((this.RetrieveOrdersOperationCompleted == null)) {
                this.RetrieveOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveOrdersOperationCompleted);
            }
            this.InvokeAsync("RetrieveOrders", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        iSourceID,
                        sOption,
                        iOrderID,
                        bUseBatchID,
                        sBatch}, this.RetrieveOrdersOperationCompleted, userState);
        }
        
        private void OnRetrieveOrdersOperationCompleted(object arg) {
            if ((this.RetrieveOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveOrdersCompleted(this, new RetrieveOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/wsSupplier/SearchOrders", RequestNamespace="http://clearstar.net/Gateway/wsSupplier/", ResponseNamespace="http://clearstar.net/Gateway/wsSupplier/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode SearchOrders(string sUserName, string sPassword, int iBOID, int iSourceID, string sSearchValue, string sSearchField, bool bExactMatch) {
            object[] results = this.Invoke("SearchOrders", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        iSourceID,
                        sSearchValue,
                        sSearchField,
                        bExactMatch});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void SearchOrdersAsync(string sUserName, string sPassword, int iBOID, int iSourceID, string sSearchValue, string sSearchField, bool bExactMatch) {
            this.SearchOrdersAsync(sUserName, sPassword, iBOID, iSourceID, sSearchValue, sSearchField, bExactMatch, null);
        }
        
        /// <remarks/>
        public void SearchOrdersAsync(string sUserName, string sPassword, int iBOID, int iSourceID, string sSearchValue, string sSearchField, bool bExactMatch, object userState) {
            if ((this.SearchOrdersOperationCompleted == null)) {
                this.SearchOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchOrdersOperationCompleted);
            }
            this.InvokeAsync("SearchOrders", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        iSourceID,
                        sSearchValue,
                        sSearchField,
                        bExactMatch}, this.SearchOrdersOperationCompleted, userState);
        }
        
        private void OnSearchOrdersOperationCompleted(object arg) {
            if ((this.SearchOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchOrdersCompleted(this, new SearchOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/wsSupplier/SaveOrderResults", RequestNamespace="http://clearstar.net/Gateway/wsSupplier/", ResponseNamespace="http://clearstar.net/Gateway/wsSupplier/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode SaveOrderResults(string sUserName, string sPassword, int iBOID, int iSourceID, int iOrderID, string sResults, bool bHit) {
            object[] results = this.Invoke("SaveOrderResults", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        iSourceID,
                        iOrderID,
                        sResults,
                        bHit});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void SaveOrderResultsAsync(string sUserName, string sPassword, int iBOID, int iSourceID, int iOrderID, string sResults, bool bHit) {
            this.SaveOrderResultsAsync(sUserName, sPassword, iBOID, iSourceID, iOrderID, sResults, bHit, null);
        }
        
        /// <remarks/>
        public void SaveOrderResultsAsync(string sUserName, string sPassword, int iBOID, int iSourceID, int iOrderID, string sResults, bool bHit, object userState) {
            if ((this.SaveOrderResultsOperationCompleted == null)) {
                this.SaveOrderResultsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveOrderResultsOperationCompleted);
            }
            this.InvokeAsync("SaveOrderResults", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        iSourceID,
                        iOrderID,
                        sResults,
                        bHit}, this.SaveOrderResultsOperationCompleted, userState);
        }
        
        private void OnSaveOrderResultsOperationCompleted(object arg) {
            if ((this.SaveOrderResultsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveOrderResultsCompleted(this, new SaveOrderResultsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/wsSupplier/SaveOrderResultsDraftProfile", RequestNamespace="http://clearstar.net/Gateway/wsSupplier/", ResponseNamespace="http://clearstar.net/Gateway/wsSupplier/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode SaveOrderResultsDraftProfile(string sUserName, string sPassword, int iBOID, int iSourceID, int iOrderID, string sResults, bool bHit) {
            object[] results = this.Invoke("SaveOrderResultsDraftProfile", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        iSourceID,
                        iOrderID,
                        sResults,
                        bHit});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void SaveOrderResultsDraftProfileAsync(string sUserName, string sPassword, int iBOID, int iSourceID, int iOrderID, string sResults, bool bHit) {
            this.SaveOrderResultsDraftProfileAsync(sUserName, sPassword, iBOID, iSourceID, iOrderID, sResults, bHit, null);
        }
        
        /// <remarks/>
        public void SaveOrderResultsDraftProfileAsync(string sUserName, string sPassword, int iBOID, int iSourceID, int iOrderID, string sResults, bool bHit, object userState) {
            if ((this.SaveOrderResultsDraftProfileOperationCompleted == null)) {
                this.SaveOrderResultsDraftProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveOrderResultsDraftProfileOperationCompleted);
            }
            this.InvokeAsync("SaveOrderResultsDraftProfile", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        iSourceID,
                        iOrderID,
                        sResults,
                        bHit}, this.SaveOrderResultsDraftProfileOperationCompleted, userState);
        }
        
        private void OnSaveOrderResultsDraftProfileOperationCompleted(object arg) {
            if ((this.SaveOrderResultsDraftProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveOrderResultsDraftProfileCompleted(this, new SaveOrderResultsDraftProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/wsSupplier/SaveOrderStatus", RequestNamespace="http://clearstar.net/Gateway/wsSupplier/", ResponseNamespace="http://clearstar.net/Gateway/wsSupplier/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode SaveOrderStatus(string sUserName, string sPassword, int iBOID, int iSourceID, int iOrderID, string sStatusDetail) {
            object[] results = this.Invoke("SaveOrderStatus", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        iSourceID,
                        iOrderID,
                        sStatusDetail});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void SaveOrderStatusAsync(string sUserName, string sPassword, int iBOID, int iSourceID, int iOrderID, string sStatusDetail) {
            this.SaveOrderStatusAsync(sUserName, sPassword, iBOID, iSourceID, iOrderID, sStatusDetail, null);
        }
        
        /// <remarks/>
        public void SaveOrderStatusAsync(string sUserName, string sPassword, int iBOID, int iSourceID, int iOrderID, string sStatusDetail, object userState) {
            if ((this.SaveOrderStatusOperationCompleted == null)) {
                this.SaveOrderStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveOrderStatusOperationCompleted);
            }
            this.InvokeAsync("SaveOrderStatus", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        iSourceID,
                        iOrderID,
                        sStatusDetail}, this.SaveOrderStatusOperationCompleted, userState);
        }
        
        private void OnSaveOrderStatusOperationCompleted(object arg) {
            if ((this.SaveOrderStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveOrderStatusCompleted(this, new SaveOrderStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/wsSupplier/GetOrderDocuments", RequestNamespace="http://clearstar.net/Gateway/wsSupplier/", ResponseNamespace="http://clearstar.net/Gateway/wsSupplier/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetOrderDocuments(string sUserName, string sPassword, int iBOID, int iSourceID, int iOrderID) {
            object[] results = this.Invoke("GetOrderDocuments", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        iSourceID,
                        iOrderID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderDocumentsAsync(string sUserName, string sPassword, int iBOID, int iSourceID, int iOrderID) {
            this.GetOrderDocumentsAsync(sUserName, sPassword, iBOID, iSourceID, iOrderID, null);
        }
        
        /// <remarks/>
        public void GetOrderDocumentsAsync(string sUserName, string sPassword, int iBOID, int iSourceID, int iOrderID, object userState) {
            if ((this.GetOrderDocumentsOperationCompleted == null)) {
                this.GetOrderDocumentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderDocumentsOperationCompleted);
            }
            this.InvokeAsync("GetOrderDocuments", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        iSourceID,
                        iOrderID}, this.GetOrderDocumentsOperationCompleted, userState);
        }
        
        private void OnGetOrderDocumentsOperationCompleted(object arg) {
            if ((this.GetOrderDocumentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderDocumentsCompleted(this, new GetOrderDocumentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/wsSupplier/GetInternalSupplierOrderSummary", RequestNamespace="http://clearstar.net/Gateway/wsSupplier/", ResponseNamespace="http://clearstar.net/Gateway/wsSupplier/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetInternalSupplierOrderSummary(string sUserName, string sPassword, int iBOID, string sCustID, int iParentSourceID) {
            object[] results = this.Invoke("GetInternalSupplierOrderSummary", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iParentSourceID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetInternalSupplierOrderSummaryAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iParentSourceID) {
            this.GetInternalSupplierOrderSummaryAsync(sUserName, sPassword, iBOID, sCustID, iParentSourceID, null);
        }
        
        /// <remarks/>
        public void GetInternalSupplierOrderSummaryAsync(string sUserName, string sPassword, int iBOID, string sCustID, int iParentSourceID, object userState) {
            if ((this.GetInternalSupplierOrderSummaryOperationCompleted == null)) {
                this.GetInternalSupplierOrderSummaryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInternalSupplierOrderSummaryOperationCompleted);
            }
            this.InvokeAsync("GetInternalSupplierOrderSummary", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID,
                        iParentSourceID}, this.GetInternalSupplierOrderSummaryOperationCompleted, userState);
        }
        
        private void OnGetInternalSupplierOrderSummaryOperationCompleted(object arg) {
            if ((this.GetInternalSupplierOrderSummaryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInternalSupplierOrderSummaryCompleted(this, new GetInternalSupplierOrderSummaryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/wsSupplier/GetExternalSupplierOrderSummary", RequestNamespace="http://clearstar.net/Gateway/wsSupplier/", ResponseNamespace="http://clearstar.net/Gateway/wsSupplier/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetExternalSupplierOrderSummary(string sUserName, string sPassword, int iBOID, string sCustID) {
            object[] results = this.Invoke("GetExternalSupplierOrderSummary", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetExternalSupplierOrderSummaryAsync(string sUserName, string sPassword, int iBOID, string sCustID) {
            this.GetExternalSupplierOrderSummaryAsync(sUserName, sPassword, iBOID, sCustID, null);
        }
        
        /// <remarks/>
        public void GetExternalSupplierOrderSummaryAsync(string sUserName, string sPassword, int iBOID, string sCustID, object userState) {
            if ((this.GetExternalSupplierOrderSummaryOperationCompleted == null)) {
                this.GetExternalSupplierOrderSummaryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetExternalSupplierOrderSummaryOperationCompleted);
            }
            this.InvokeAsync("GetExternalSupplierOrderSummary", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        sCustID}, this.GetExternalSupplierOrderSummaryOperationCompleted, userState);
        }
        
        private void OnGetExternalSupplierOrderSummaryOperationCompleted(object arg) {
            if ((this.GetExternalSupplierOrderSummaryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetExternalSupplierOrderSummaryCompleted(this, new GetExternalSupplierOrderSummaryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/wsSupplier/GetListOfOrdersForSupplier", RequestNamespace="http://clearstar.net/Gateway/wsSupplier/", ResponseNamespace="http://clearstar.net/Gateway/wsSupplier/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetListOfOrdersForSupplier(string sUserName, string sPassword, int iBOID, int iSourceID, string sSourceName, int iOrderStatus, string sOrderBY, bool bSortInAscending, string sFilterBy, string sIncludeInReview, int iStartAtRecord, int iMaxResults) {
            object[] results = this.Invoke("GetListOfOrdersForSupplier", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        iSourceID,
                        sSourceName,
                        iOrderStatus,
                        sOrderBY,
                        bSortInAscending,
                        sFilterBy,
                        sIncludeInReview,
                        iStartAtRecord,
                        iMaxResults});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetListOfOrdersForSupplierAsync(string sUserName, string sPassword, int iBOID, int iSourceID, string sSourceName, int iOrderStatus, string sOrderBY, bool bSortInAscending, string sFilterBy, string sIncludeInReview, int iStartAtRecord, int iMaxResults) {
            this.GetListOfOrdersForSupplierAsync(sUserName, sPassword, iBOID, iSourceID, sSourceName, iOrderStatus, sOrderBY, bSortInAscending, sFilterBy, sIncludeInReview, iStartAtRecord, iMaxResults, null);
        }
        
        /// <remarks/>
        public void GetListOfOrdersForSupplierAsync(string sUserName, string sPassword, int iBOID, int iSourceID, string sSourceName, int iOrderStatus, string sOrderBY, bool bSortInAscending, string sFilterBy, string sIncludeInReview, int iStartAtRecord, int iMaxResults, object userState) {
            if ((this.GetListOfOrdersForSupplierOperationCompleted == null)) {
                this.GetListOfOrdersForSupplierOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListOfOrdersForSupplierOperationCompleted);
            }
            this.InvokeAsync("GetListOfOrdersForSupplier", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        iSourceID,
                        sSourceName,
                        iOrderStatus,
                        sOrderBY,
                        bSortInAscending,
                        sFilterBy,
                        sIncludeInReview,
                        iStartAtRecord,
                        iMaxResults}, this.GetListOfOrdersForSupplierOperationCompleted, userState);
        }
        
        private void OnGetListOfOrdersForSupplierOperationCompleted(object arg) {
            if ((this.GetListOfOrdersForSupplierCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListOfOrdersForSupplierCompleted(this, new GetListOfOrdersForSupplierCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clearstar.net/Gateway/wsSupplier/GetNewOrdersMarkInProgress", RequestNamespace="http://clearstar.net/Gateway/wsSupplier/", ResponseNamespace="http://clearstar.net/Gateway/wsSupplier/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetNewOrdersMarkInProgress(string sUserName, string sPassword, int iBOID, int iSourceID, string sOption, int iOrderID) {
            object[] results = this.Invoke("GetNewOrdersMarkInProgress", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        iSourceID,
                        sOption,
                        iOrderID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetNewOrdersMarkInProgressAsync(string sUserName, string sPassword, int iBOID, int iSourceID, string sOption, int iOrderID) {
            this.GetNewOrdersMarkInProgressAsync(sUserName, sPassword, iBOID, iSourceID, sOption, iOrderID, null);
        }
        
        /// <remarks/>
        public void GetNewOrdersMarkInProgressAsync(string sUserName, string sPassword, int iBOID, int iSourceID, string sOption, int iOrderID, object userState) {
            if ((this.GetNewOrdersMarkInProgressOperationCompleted == null)) {
                this.GetNewOrdersMarkInProgressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNewOrdersMarkInProgressOperationCompleted);
            }
            this.InvokeAsync("GetNewOrdersMarkInProgress", new object[] {
                        sUserName,
                        sPassword,
                        iBOID,
                        iSourceID,
                        sOption,
                        iOrderID}, this.GetNewOrdersMarkInProgressOperationCompleted, userState);
        }
        
        private void OnGetNewOrdersMarkInProgressOperationCompleted(object arg) {
            if ((this.GetNewOrdersMarkInProgressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNewOrdersMarkInProgressCompleted(this, new GetNewOrdersMarkInProgressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetServiceMacrosCompletedEventHandler(object sender, GetServiceMacrosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServiceMacrosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServiceMacrosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void RetrieveOrdersCompletedEventHandler(object sender, RetrieveOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SearchOrdersCompletedEventHandler(object sender, SearchOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SaveOrderResultsCompletedEventHandler(object sender, SaveOrderResultsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveOrderResultsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveOrderResultsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SaveOrderResultsDraftProfileCompletedEventHandler(object sender, SaveOrderResultsDraftProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveOrderResultsDraftProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveOrderResultsDraftProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SaveOrderStatusCompletedEventHandler(object sender, SaveOrderStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveOrderStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveOrderStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetOrderDocumentsCompletedEventHandler(object sender, GetOrderDocumentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderDocumentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderDocumentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetInternalSupplierOrderSummaryCompletedEventHandler(object sender, GetInternalSupplierOrderSummaryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInternalSupplierOrderSummaryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInternalSupplierOrderSummaryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetExternalSupplierOrderSummaryCompletedEventHandler(object sender, GetExternalSupplierOrderSummaryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetExternalSupplierOrderSummaryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetExternalSupplierOrderSummaryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetListOfOrdersForSupplierCompletedEventHandler(object sender, GetListOfOrdersForSupplierCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListOfOrdersForSupplierCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListOfOrdersForSupplierCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetNewOrdersMarkInProgressCompletedEventHandler(object sender, GetNewOrdersMarkInProgressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNewOrdersMarkInProgressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNewOrdersMarkInProgressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591