//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surpath.Clearstar.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://Gateway.clearstar.net/CSGWCustomer/Customer.asmx")]
        public string Surpath_Clearstar_CS_Customer_Customer {
            get {
                return ((string)(this["Surpath_Clearstar_CS_Customer_Customer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://gateway.clearstar.net/csgwDocument/Document.asmx")]
        public string Surpath_Clearstar_CS_Document_Document {
            get {
                return ((string)(this["Surpath_Clearstar_CS_Document_Document"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://gateway.clearstar.net/csgwInvoice/Invoice.asmx")]
        public string Surpath_Clearstar_CS_Invoice_Invoice {
            get {
                return ((string)(this["Surpath_Clearstar_CS_Invoice_Invoice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://gateway.clearstar.net/csgwLookup/Lookup.asmx")]
        public string Surpath_Clearstar_CS_Lookup_LookUp {
            get {
                return ((string)(this["Surpath_Clearstar_CS_Lookup_LookUp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://gateway.clearstar.net/csgwMacro/Macro.asmx")]
        public string Surpath_Clearstar_net_clearstar_gateway_Macro {
            get {
                return ((string)(this["Surpath_Clearstar_net_clearstar_gateway_Macro"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://gateway.clearstar.net/CSGWMFA/MFA.asmx")]
        public string Surpath_Clearstar_CS_MFA_MFA {
            get {
                return ((string)(this["Surpath_Clearstar_CS_MFA_MFA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://gateway.clearstar.net/csgworder/order.asmx")]
        public string Surpath_Clearstar_CS_Order_Order {
            get {
                return ((string)(this["Surpath_Clearstar_CS_Order_Order"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://gateway.clearstar.net/CSGWPostMaster/PostMaster.asmx")]
        public string Surpath_Clearstar_CS_PostMaster_PostMaster {
            get {
                return ((string)(this["Surpath_Clearstar_CS_PostMaster_PostMaster"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://gateway.clearstar.net/csgwservice/service.asmx")]
        public string Surpath_Clearstar_CS_Service_Service {
            get {
                return ((string)(this["Surpath_Clearstar_CS_Service_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://gateway.clearstar.net/csgwStreamline/Streamline.asmx")]
        public string Surpath_Clearstar_CS_Streamline_Streamline {
            get {
                return ((string)(this["Surpath_Clearstar_CS_Streamline_Streamline"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://gateway.clearstar.net/CSGWSupplier/Supplier.asmx")]
        public string Surpath_Clearstar_CS_Supplier_Supplier {
            get {
                return ((string)(this["Surpath_Clearstar_CS_Supplier_Supplier"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://gateway.clearstar.net/csgwUser/User.asmx")]
        public string Surpath_Clearstar_CS_User_User {
            get {
                return ((string)(this["Surpath_Clearstar_CS_User_User"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://gateway.clearstar.net/CSGWProfile/Profile.asmx")]
        public string Surpath_Clearstar_CS_Profile_Profile {
            get {
                return ((string)(this["Surpath_Clearstar_CS_Profile_Profile"]));
            }
        }
    }
}
